name: BetterBeds
main: de.themoep.BetterBeds.BetterBeds
version: 0.4
description: Better bed and sleeping handling for large servers
authors: [Phoenix616]
website: http://dev.bukkit.org/bukkit-plugins/betterbeds/
commands:
   betterbedsreload:
      aliases: [bbreload]
      description: Reloads the config from the configfile.
      usage: /<command>
      permission: betterbeds.cmd.reload
      permission-message: You don't have the permission <permission>
permissions:
   betterbeds.cmd.reload:
      description: Gives permission to the reload command
      default: op
   betterbeds.ghost:
      description: Makes player to a ghost
      default: none
   betterbeds.sleep:
      description: Gives user ability to sleep
      default: op
   betterbeds.ignore:
      description: Users with this permission don't get calculated when they are online.
      default: op
